CREATE DATABASE EXAMES;

USE EXAMES;

CREATE TABLE PACIENTE (
PAC_CODIGO_PK INT PRIMARY KEY NOT NULL IDENTITY(1,1),
PAC_NOME VARCHAR(100),
PAC_CPF VARCHAR(11),
PAC_DATA_NASCIMENTO DATE,
PAC_SEXO VARCHAR(15),
PAC_TELEFONE VARCHAR(11),
PAC_EMAIL VARCHAR(60)
)

CREATE TABLE TIPO_EXAME (
TIE_CODIGO_PK INT PRIMARY KEY NOT NULL IDENTITY(1,1),
TIE_NOME VARCHAR(100),
TIE_DESCRICAO VARCHAR(256)
)

CREATE TABLE EXAME (
EXA_CODIGO_PK INT PRIMARY KEY NOT NULL IDENTITY(1,1),
EXA_NOME VARCHAR(100),
EXA_OBSERVACAO TEXT,
EXA_TIE_CODIGO_FK INT NOT NULL,
CONSTRAINT FK_TIPO_EXAME FOREIGN KEY (EXA_TIE_CODIGO_FK) REFERENCES TIPO_EXAME (TIE_CODIGO_PK)
ON UPDATE CASCADE
ON DELETE CASCADE
)


CREATE TABLE CONSULTA (
CON_CODIGO_PK INT PRIMARY KEY NOT NULL IDENTITY(1,1),
CON_PAC_CODIGO_FK INT NOT NULL,
CON_TIE_CODIGO_FK INT NOT NULL,
CON_DATA DATE,
CON_HORA TIME,
CON_PROTOCOLO INT
CONSTRAINT FK_PACIENTE FOREIGN KEY (CON_PAC_CODIGO_FK) REFERENCES PACIENTE (PAC_CODIGO_PK),
CONSTRAINT FK_TIPO_EXAME_CONSULTA FOREIGN KEY (CON_TIE_CODIGO_FK) REFERENCES TIPO_EXAME (TIE_CODIGO_PK)
ON UPDATE CASCADE
ON DELETE CASCADE
)


CREATE TABLE USUARIO (
USU_CODIGO_PK INT PRIMARY KEY NOT NULL IDENTITY(1,1),
USU_NOME VARCHAR(100) NOT NULL,
USU_EMAIL VARCHAR(60) NOT NULL,
USU_SENHA VARCHAR(100)
)

